2019-10-10 10:37:02.297 [error] <0.245.0> gen_server <0.245.0> terminated with reason: socket_closed_unexpectedly
2019-10-10 10:37:02.301 [error] <0.245.0> CRASH REPORT Process <0.245.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 751
2019-10-10 10:37:02.301 [error] <0.243.0> Supervisor {<0.243.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.244.0>, {amqp_params_network,<<"rabbitmq">>,<<"rabbitmq">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun a..>,...],...}) at <0.245.0> exit with reason socket_closed_unexpectedly in context child_terminated
2019-10-10 10:37:02.302 [error] <0.243.0> Supervisor {<0.243.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.244.0>, {amqp_params_network,<<"rabbitmq">>,<<"rabbitmq">>,<<"/">>,"localhost",5672,0,0,10,50000,none,[fun a..>,...],...}) at <0.245.0> exit with reason reached_max_restart_intensity in context shutdown
2019-10-10 14:11:05.192 [error] <0.248.0> Supervisor {<0.248.0>,amqp_channel_sup_sup} had child channel_sup started with amqp_channel_sup:start_link(network, <0.245.0>, <<"client 127.0.0.1:34349 -> 127.0.0.1:5672">>) at undefined exit with reason noproc in context shutdown_error
